-- MySQL Script generated by MySQL Workbench
-- Sat Mar 26 16:09:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotelman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotelman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotelman` DEFAULT CHARACTER SET utf8 ;
USE `hotelman` ;

-- -----------------------------------------------------
-- Table `hotelman`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelman`.`room` ;

CREATE TABLE IF NOT EXISTS `hotelman`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomnr` INT NULL,
  `price` INT NULL,
  `nr_guests` INT NULL,
  `category` VARCHAR(45) NULL,
  `extra` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelman`.`guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelman`.`guest` ;

CREATE TABLE IF NOT EXISTS `hotelman`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `e-mail` VARCHAR(100) CHARACTER SET 'armscii8' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotelman`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotelman`.`booking` ;

CREATE TABLE IF NOT EXISTS `hotelman`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guest_id` INT NULL,
  `room_id` INT NULL,
  `price` INT NULL,
  `beginning` DATE NULL,
  `end` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_guest`
    FOREIGN KEY (`id`)
    REFERENCES `hotelman`.`guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room`
    FOREIGN KEY (`id`)
    REFERENCES `hotelman`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
